Repository PagerDuty/incident-response-docs, pull requests merged in 2019-01, with the labels that each got.

#83 Remove and update confusing voice pattern in silence section
  docs/resources/anti_patterns.md
Labels: typo / bug

#92 Add some extra links to our training course.
  docs/index.md
  docs/training/courses/incident_response.md
Labels: enhancement / new section

#93 Add PyMdown Extensions to development readme
  README.md
Labels: typo / bug

#94 Remove robots meta tag and add a robots.txt file.
  theme/base.html
  theme/robots.txt
Labels: operational
